import type {
    ArcGISField,
    ArcGISQueryOptions,
    ArcGISQueryResult
} from "./types.js";


// =============================================================================
// Types
// =============================================================================

export interface ArcGISQueryFeature {

    attributes:
        Record<string, unknown>;

    geometry?:
        unknown;
}


interface ArcGISQueryResponse {

    error?: {
        code?:
            number;

        message?:
            string;

        details?:
            string[];
    };

    features?: Array<{
        attributes?:
            Record<string, unknown>;

        geometry?:
            unknown;
    }>;

    fields?: Array<{
        name?:
            string;

        alias?:
            string;

        type?:
            string;

        length?:
            number;

        domain?:
            unknown;
    }>;

    exceededTransferLimit?:
        boolean;
}


// =============================================================================
// Fetch type
// =============================================================================

type FetchLike = (
    input:
        string | URL | Request,

    init?:
        RequestInit
) => Promise<Response>;


// =============================================================================
// Constants
// =============================================================================

/**
 * Maximum number of pages that a fetchAll query may retrieve.
 *
 * This is a safety guard for ArcGIS services that incorrectly report
 * exceededTransferLimit or ignore resultOffset.
 */
const MAX_PAGES =
    1000;


// =============================================================================
// Public API
// =============================================================================

export async function queryArcGISLayer(
    url: string,
    options:
        ArcGISQueryOptions = {},
    fetchImpl:
        FetchLike = fetch
): Promise<ArcGISQueryResult> {

    const normalizedUrl =
        normalizeUrl(url);

    const resultRecordCount =
        options.resultRecordCount ??
        100;

    const initialResultOffset =
        options.resultOffset ??
        0;

    const returnGeometry =
        options.returnGeometry ??
        false;

    const maxUniqueValues =
        options.maxUniqueValues ??
        100;

    const fetchAll =
        options.fetchAll ??
        false;

    const outFields =
        options.outFields &&
        options.outFields.length > 0
            ? options.outFields.join(",")
            : "*";

    const where =
        options.where ??
        "1=1";

    /*
     * WGS 84 / EPSG:4326 is the canonical coordinate
     * system used by GeoJSON and by the Census geometries
     * generated by this package.
     *
     * Only request an output spatial reference when
     * geometry is being returned.
     */
    const outSR =
        returnGeometry
            ? options.outSR ?? 4326
            : undefined;

    /*
     * Ordinary queries retain the original single-page behavior.
     *
     * This is important because geometry generation and other
     * bounded queries should not unexpectedly retrieve an entire
     * ArcGIS layer.
     */
    if (!fetchAll) {

        return queryPage(
            normalizedUrl,
            {
                where,
                outFields,
                resultRecordCount,
                resultOffset:
                    initialResultOffset,
                returnGeometry,
                outSR,
                maxUniqueValues
            },
            fetchImpl
        );
    }

    /*
     * fetchAll is intentionally implemented separately from the
     * normal single-page path.
     *
     * This allows callers such as municipality completeness
     * validation to explicitly request the entire layer without
     * changing the behavior of ordinary ArcGIS queries.
     */
    return queryAllPages(
        normalizedUrl,
        {
            where,
            outFields,
            resultRecordCount,
            resultOffset:
                initialResultOffset,
            returnGeometry,
            outSR,
            maxUniqueValues
        },
        fetchImpl
    );
}


// =============================================================================
// Query parameters
// =============================================================================

interface QueryParameters {

    where:
        string;

    outFields:
        string;

    resultRecordCount:
        number;

    resultOffset:
        number;

    returnGeometry:
        boolean;

    outSR?:
        number;
}


interface PageQueryParameters
    extends QueryParameters {

    maxUniqueValues:
        number;
}


// =============================================================================
// Single-page query
// =============================================================================

async function queryPage(
    url:
        string,

    parameters:
        PageQueryParameters,

    fetchImpl:
        FetchLike
): Promise<ArcGISQueryResult> {

    const queryUrl =
        buildQueryUrl(
            url,
            parameters
        );

    try {

        const response =
            await fetchImpl(
                queryUrl,
                {
                    headers: {
                        Accept:
                            "application/json"
                    }
                }
            );

        if (!response.ok) {

            return createFailedResult(
                url,
                [
                    "ArcGIS query failed.",
                    `Status: ${response.status}`,
                    `Status text: ${response.statusText}`
                ].join(" ")
            );
        }

        const json =
            await response.json() as ArcGISQueryResponse;

        if (json.error) {

            return createFailedResult(
                url,
                [
                    `ArcGIS error ${json.error.code ?? ""}`.trim(),
                    json.error.message ?? "",
                    ...(json.error.details ?? [])
                ]
                    .filter(Boolean)
                    .join(" ")
            );
        }

        const features =
            normalizeFeatures(
                json.features
            );

        const fields =
            normalizeFields(
                json.fields
            );

        const uniqueValues =
            collectUniqueValues(
                features,
                parameters.maxUniqueValues
            );

        return {

            url,

            success:
                true,

            features,

            featureCount:
                features.length,

            exceededTransferLimit:
                Boolean(
                    json.exceededTransferLimit
                ),

            fields,

            uniqueValues
        };

    } catch (error) {

        return createFailedResult(
            url,
            error instanceof Error
                ? error.message
                : String(error)
        );
    }
}


// =============================================================================
// Paginated query
// =============================================================================

async function queryAllPages(
    url:
        string,

    parameters:
        PageQueryParameters,

    fetchImpl:
        FetchLike
): Promise<ArcGISQueryResult> {

    const allFeatures:
        ArcGISQueryFeature[] = [];

    const allUniqueValues:
        Record<string, unknown[]> = {};

    let fields:
        ArcGISField[] = [];

    let resultOffset =
        parameters.resultOffset;

    let exceededTransferLimit =
        true;

    let pageCount =
        0;

    let previousPageSignature:
        string | undefined;

    while (exceededTransferLimit) {

        pageCount += 1;

        if (pageCount > MAX_PAGES) {

            return createFailedResult(
                url,
                [
                    "ArcGIS pagination exceeded the maximum",
                    `page limit of ${MAX_PAGES}.`
                ].join(" ")
            );
        }

        const page =
            await queryPage(
                url,
                {
                    ...parameters,
                    resultOffset
                },
                fetchImpl
            );

        if (!page.success) {

            /*
             * Do not return partial data.
             *
             * A completeness check must never conclude that a
             * layer is incomplete merely because a later page
             * failed to load.
             */
            return page;
        }

        if (pageCount === 1) {

            fields =
                page.fields;
        }

        /*
         * Protect against services that report
         * exceededTransferLimit but ignore resultOffset.
         *
         * Such a service could otherwise return the same page
         * forever.
         */
        const pageSignature =
            createPageSignature(
                page.features
            );

        if (
            previousPageSignature !== undefined &&
            pageSignature === previousPageSignature
        ) {

            return createFailedResult(
                url,
                [
                    "ArcGIS pagination did not advance.",
                    "The service may not support result offsets."
                ].join(" ")
            );
        }

        previousPageSignature =
            pageSignature;

        allFeatures.push(
            ...page.features
        );

        mergeUniqueValues(
            allUniqueValues,
            page.uniqueValues,
            parameters.maxUniqueValues
        );

        exceededTransferLimit =
            page.exceededTransferLimit;

        /*
         * Advance by the number of features actually returned,
         * rather than blindly adding resultRecordCount.
         *
         * This handles a final partial page correctly.
         */
        if (
            exceededTransferLimit
        ) {

            if (
                page.features.length === 0
            ) {

                return createFailedResult(
                    url,
                    [
                        "ArcGIS pagination reported",
                        "exceededTransferLimit but returned",
                        "no features."
                    ].join(" ")
                );
            }

            resultOffset +=
                page.features.length;
        }
    }

    return {

        url,

        success:
            true,

        features:
            allFeatures,

        featureCount:
            allFeatures.length,

        exceededTransferLimit:
            false,

        fields,

        uniqueValues:
            allUniqueValues
    };
}


// =============================================================================
// Query URL
// =============================================================================

function buildQueryUrl(
    url: string,
    parameters:
        QueryParameters
): string {

    const query =
        new URLSearchParams();

    query.set(
        "where",
        parameters.where
    );

    query.set(
        "outFields",
        parameters.outFields
    );

    query.set(
        "returnGeometry",
        parameters.returnGeometry
            ? "true"
            : "false"
    );

    query.set(
        "f",
        "json"
    );

    query.set(
        "resultRecordCount",
        String(
            parameters.resultRecordCount
        )
    );

    query.set(
        "resultOffset",
        String(
            parameters.resultOffset
        )
    );

    if (
        parameters.outSR !== undefined
    ) {

        query.set(
            "outSR",
            String(
                parameters.outSR
            )
        );
    }

    return (
        `${url}/query?${query.toString()}`
    );
}


// =============================================================================
// Feature normalization
// =============================================================================

function normalizeFeatures(
    features:
        | ArcGISQueryResponse["features"]
        | undefined
): ArcGISQueryFeature[] {

    if (!Array.isArray(features)) {
        return [];
    }

    return features
        .filter(
            feature =>
                feature &&
                typeof feature === "object"
        )
        .map(
            feature => ({

                attributes:
                    feature.attributes ?? {},

                ...(feature.geometry !== undefined
                    ? {
                        geometry:
                            feature.geometry
                    }
                    : {})
            })
        );
}


// =============================================================================
// Field normalization
// =============================================================================

function normalizeFields(
    fields:
        | ArcGISQueryResponse["fields"]
        | undefined
): ArcGISField[] {

    if (!Array.isArray(fields)) {
        return [];
    }

    return fields
        .filter(
            field =>
                typeof field.name === "string" &&
                field.name.trim().length > 0
        )
        .map(
            field => {

                const name =
                    field.name!.trim();

                return {

                    name,

                    ...(field.alias &&
                        field.alias.trim().length > 0
                        ? {
                            alias:
                                field.alias.trim()
                        }
                        : {}),

                    ...(field.type
                        ? {
                            type:
                                field.type
                        }
                        : {}),

                    ...(typeof field.length === "number"
                        ? {
                            length:
                                field.length
                        }
                        : {}),

                    ...(field.domain !== undefined
                        ? {
                            domain:
                                field.domain
                        }
                        : {})
                };
            }
        );
}


// =============================================================================
// Unique values
// =============================================================================

function collectUniqueValues(
    features:
        ArcGISQueryFeature[],

    maxUniqueValues:
        number
): Record<string, unknown[]> {

    const values =
        new Map<
            string,
            Set<string>
        >();

    for (
        const feature
            of features
    ) {

        for (
            const [
                field,
                value
            ]
                of Object.entries(
                    feature.attributes
                )
        ) {

            if (
                value === null ||
                value === undefined ||
                value === ""
            ) {
                continue;
            }

            if (!values.has(field)) {

                values.set(
                    field,
                    new Set()
                );
            }

            const set =
                values.get(field)!;

            if (
                set.size <
                maxUniqueValues
            ) {

                set.add(
                    String(value)
                );
            }
        }
    }

    const result:
        Record<string, unknown[]> = {};

    for (
        const [
            field,
            set
        ]
            of values
    ) {

        result[field] =
            Array.from(set);
    }

    return result;
}


// =============================================================================
// Merge unique values
// =============================================================================

function mergeUniqueValues(
    target:
        Record<string, unknown[]>,

    source:
        Record<string, unknown[]>,

    maxUniqueValues:
        number
): void {

    for (
        const [
            field,
            values
        ]
            of Object.entries(source)
    ) {

        if (
            !target[field]
        ) {

            target[field] =
                [];
        }

        const existing =
            new Set(
                target[field].map(
                    value =>
                        String(value)
                )
            );

        for (
            const value
                of values
        ) {

            if (
                existing.size >=
                maxUniqueValues
            ) {
                break;
            }

            const normalized =
                String(value);

            if (
                !existing.has(
                    normalized
                )
            ) {

                existing.add(
                    normalized
                );

                target[field].push(
                    value
                );
            }
        }
    }
}


// =============================================================================
// Page signature
// =============================================================================

function createPageSignature(
    features:
        ArcGISQueryFeature[]
): string {

    /*
     * This is deliberately based on the returned feature content
     * rather than requiring OBJECTID to be present in outFields.
     *
     * That keeps queryArcGISLayer() generic across ArcGIS layers.
     */
    return JSON.stringify(
        features
    );
}


// =============================================================================
// Failed result
// =============================================================================

function createFailedResult(
    url:
        string,

    error:
        string
): ArcGISQueryResult {

    return {

        url,

        success:
            false,

        features:
            [],

        featureCount:
            0,

        exceededTransferLimit:
            false,

        fields:
            [],

        uniqueValues:
            {},

        error
    };
}


// =============================================================================
// URL normalization
// =============================================================================

function normalizeUrl(
    url:
        string
): string {

    return url
        .trim()
        .replace(
            /\/+$/,
            ""
        );
}